with open("c:/Users/lenovo/Desktop/alltoools/Goldbot/bot_spot.py", "r", encoding="utf-8") as f:
    text = f.read()

import re

# Fix literal newlines inside python strings
# Find all occurrences where a string ends prematurely with a newline, followed by a double quote on the next line.
text = text.replace('"\n".join(', '"\\n".join(')
text = text.replace('"\n        "', '"\\n        "')
text = text.replace('👑\n"        "', '👑\\n"        "')
text = text.replace('📊\n"        f"💰', '📊\\n"        f"💰')
text = text.replace('$\n"        f"📏', '$\\n"        f"📏')
text = text.replace('$\n"        f"⚖️', '$\\n"        f"⚖️')
text = text.replace('$\n"        f"📉', '$\\n"        f"📉')
text = text.replace('$\n"        f"📈', '$\\n"        f"📈')
text = text.replace('$\n"        "━', '$\\n"        "━')
text = text.replace('━\n"        "⏱️', '━\\n"        "⏱️')
text = text.replace('ب\n"        f"🔹', 'ب\\n"        f"🔹')
text = text.replace(')\n"        f"🔹', ')\\n"        f"🔹')
text = text.replace(')\n"        "━', ')\\n"        "━')
text = text.replace('━\n"        "📐', '━\\n"        "📐')
text = text.replace(')\n"        f"{', ')\\n"        f"{')
text = text.replace('}\n"        "━', '}\\n"        "━')
text = text.replace('━\n"        "🛡️', '━\\n"        "🛡️')
text = text.replace(')\n"        f"🔺', ')\\n"        f"🔺')
text = text.replace('$\n"        f"🔻', '$\\n"        f"🔻')
text = text.replace('$\n"        f"🔄', '$\\n"        f"🔄')
text = text.replace('━\n"        "🔬', '━\\n"        "🔬')
text = text.replace('م\n"        f"📌', 'م\\n"        f"📌')
text = text.replace('}\n"        f"📌', '}\\n"        f"📌')
text = text.replace('━\n"        "📝', '━\\n"        "📝')
text = text.replace('ي\n"        f"{', 'ي\\n"        f"{')
text = text.replace('}\n"        "⚠️', '}\\n"        "⚠️')
text = text.replace('🕒\n"        "━', '🕒\\n"        "━')
text = text.replace('━\n"        "🧭', '━\\n"        "🧭')
text = text.replace(')\n"        f"ب', ')\\n"        f"ب')
text = text.replace(']\n"        f"ب', ']\\n"        f"ب')
text = text.replace('━\n"        "🔬', '━\\n"        "🔬')
text = text.replace('}\n"        f"⏱️', '}\\n"        f"⏱️')
text = text.replace('}\n"        f"📅', '}\\n"        f"📅')
text = text.replace('}\n"        f"📆', '}\\n"        f"📆')
text = text.replace('}\n"        f"🗓️', '}\\n"        f"🗓️')
text = text.replace('━\n"        "⚖️', '━\\n"        "⚖️')
text = text.replace(')\n"        f"🔴', ')\\n"        f"🔴')
text = text.replace(')\n"        f"🔵', ')\\n"        f"🔵')
text = text.replace('$\n"        f"🟢', '$\\n"        f"🟢')
text = text.replace('━\n"        "🎯', '━\\n"        "🎯')
text = text.replace('ة\n"        f"🛒', 'ة\\n"        f"🛒')
text = text.replace('}\n"        f"📉', '}\\n"        f"📉')
text = text.replace('━\n"        "⚠️', '━\\n"        "⚠️')
text = text.replace('ي\n"        f"م', 'ي\\n"        f"م')
text = text.replace('.\n"        f"م', '.\\n"        f"م')
text = text.replace('🔍\n"        "━', '🔍\\n"        "━')
text = text.replace('━\n"        "📊', '━\\n"        "📊')
text = text.replace('$\n"        "━', '$\\n"        "━')
text = text.replace('━\n"        "🧬', '━\\n"        "🧬')
text = text.replace('ة\n"        f"📡', 'ة\\n"        f"📡')
text = text.replace('}\n"        f"📡', '}\\n"        f"📡')
text = text.replace('}\n"        f"📏', '}\\n"        f"📏')
text = text.replace(')\n"        "━', ')\\n"        "━')
text = text.replace('━\n"        "📐', '━\\n"        "📐')
text = text.replace(')\n"        f"{', ')\\n"        f"{')
text = text.replace('}\n"        "━', '}\\n"        "━')
text = text.replace('━\n"        "🎯', '━\\n"        "🎯')
text = text.replace('🎯\n"        "*', '🎯\\n"        "*')
text = text.replace(')\n\n"        f"🛒', ')\\n\\n"        f"🛒')
text = text.replace('*\n\n"        f"🛒', '*\\n\\n"        f"🛒')
text = text.replace(':\n"        f"   🔹', ':\\n"        f"   🔹')
text = text.replace('$\n"        f"   🛑', '$\\n"        f"   🛑')
text = text.replace(')\n"        f"   🎯', ')\\n"        f"   🎯')
text = text.replace('$\n\n"        f"📉', '$\\n\\n"        f"📉')
text = text.replace(':\n"        f"   🔻', ':\\n"        f"   🔻')
text = text.replace('$\n"        "━', '$\\n"        "━')

with open("c:/Users/lenovo/Desktop/alltoools/Goldbot/bot_spot.py", "w", encoding="utf-8") as f:
    f.write(text)
